//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortMainScaleTest.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ManualCOMsettings {
            get {
                return ((string)(this["ManualCOMsettings"]));
            }
            set {
                this["ManualCOMsettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLCOMsettings {
            get {
                return ((string)(this["PLCOMsettings"]));
            }
            set {
                this["PLCOMsettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int packLineNumber {
            get {
                return ((int)(this["packLineNumber"]));
            }
            set {
                this["packLineNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string locationCHKW {
            get {
                return ((string)(this["locationCHKW"]));
            }
            set {
                this["locationCHKW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxSaveToNewFormat {
            get {
                return ((bool)(this["checkBoxSaveToNewFormat"]));
            }
            set {
                this["checkBoxSaveToNewFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoGenerateReport {
            get {
                return ((bool)(this["autoGenerateReport"]));
            }
            set {
                this["autoGenerateReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int sendReportAtHour {
            get {
                return ((int)(this["sendReportAtHour"]));
            }
            set {
                this["sendReportAtHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int sendReportAtMinute {
            get {
                return ((int)(this["sendReportAtMinute"]));
            }
            set {
                this["sendReportAtMinute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isBarcodeChecker {
            get {
                return ((bool)(this["isBarcodeChecker"]));
            }
            set {
                this["isBarcodeChecker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int barcodeCheckerCount {
            get {
                return ((int)(this["barcodeCheckerCount"]));
            }
            set {
                this["barcodeCheckerCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ea")]
        public string barcodeCheckerCountType {
            get {
                return ((string)(this["barcodeCheckerCountType"]));
            }
            set {
                this["barcodeCheckerCountType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string barCodeEmailNotificationList {
            get {
                return ((string)(this["barCodeEmailNotificationList"]));
            }
            set {
                this["barCodeEmailNotificationList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string barCodeEmailNotificationListCC {
            get {
                return ((string)(this["barCodeEmailNotificationListCC"]));
            }
            set {
                this["barCodeEmailNotificationListCC"] = value;
            }
        }
    }
}
